import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDirectory, '..');
const distDirectory = path.join(projectRoot, 'dist');

function parseEnv(contents) {
  const values = {};
  for (const rawLine of contents.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const separator = line.indexOf('=');
    if (separator < 1) continue;

    const key = line.slice(0, separator).trim();
    let value = line.slice(separator + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    values[key] = value;
  }
  return values;
}

const envPath = path.join(projectRoot, '.env');
if (!fs.existsSync(envPath)) {
  throw new Error('Missing .env file. Create it from .env.example before building.');
}

const env = parseEnv(fs.readFileSync(envPath, 'utf8'));
const apiKey = env.OPENROUTER_API_KEY?.trim();
const model = env.OPENROUTER_MODEL?.trim();
if (!apiKey || !model) {
  throw new Error('OPENROUTER_API_KEY and OPENROUTER_MODEL are required in .env.');
}

fs.rmSync(distDirectory, { recursive: true, force: true });
fs.mkdirSync(distDirectory, { recursive: true });

for (const relativePath of ['manifest.json', 'ai_module', 'extension_core', 'shared_config']) {
  fs.cpSync(
    path.join(projectRoot, relativePath),
    path.join(distDirectory, relativePath),
    { recursive: true }
  );
}

const generatedConfig = [
  '/** Generated by npm run build. Do not commit this file. */',
  'export const RUNTIME_CONFIG = Object.freeze({',
  `  openRouterApiKey: ${JSON.stringify(apiKey)},`,
  `  openRouterModel: ${JSON.stringify(model)}`,
  '});',
  ''
].join('\n');

fs.writeFileSync(
  path.join(distDirectory, 'shared_config', 'runtime_config.js'),
  generatedConfig,
  'utf8'
);

console.log('Built Chrome extension in dist/. Load that folder as the unpacked extension.');
